name: airsim_env
channels:
  - defaults
dependencies:
  - ca-certificates=2025.11.4
  - libffi=3.4.4
  - openssl=3.0.18
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.51.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.44.0
  - pip:
      - airsim==1.8.1
      - msgpack-python==0.5.6
      - msgpack-rpc-python==0.4.1
      - numpy==1.24.4
      - opencv-contrib-python==4.12.0.88
      - opencv-python==4.12.0.88
      - pyzmq==27.1.0
      - tornado==4.5.3
prefix: C:\Users\Alvaro\miniconda3\envs\airsim_env
