name: drone_yolo
channels:
  - defaults
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - cpuonly=2.0
  - filelock=3.20.0
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.11
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.50
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.5
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.18
  - pillow=11.1.0
  - pip=25.2
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.11.9
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.5
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2021.8.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - click==8.3.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - fsspec==2025.10.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanfriendly==10.0
      - imageio==2.37.2
      - imgviz==1.7.6
      - iniconfig==2.3.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - labelimg==1.8.6
      - labelme==5.9.1
      - lark==1.3.1
      - lazy-loader==0.4
      - loguru==0.7.3
      - lxml==6.0.2
      - matplotlib==3.10.7
      - mistune==3.1.4
      - narwhals==2.11.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - onnxruntime==1.23.2
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - osam==0.2.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyarrow==21.0.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.1
      - pyreadline3==3.5.4
      - pytest==9.0.0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - referencing==0.37.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.28.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - streamlit==1.51.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - tinycss2==1.4.0
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.227
      - ultralytics-thop==2.0.18
      - uri-template==1.3.0
      - watchdog==6.0.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - win32-setctime==1.2.0
prefix: C:\Users\Alvaro\miniconda3\envs\drone_yolo
